version: '3.8'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:80"
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
